/**
 * detector.c — Bare-metal interference detector for Bao hypervisor
 * =================================================================
 * Implements the Phase 2 Simplified V1 MLP model in portable C99.
 *
 * Feature engineering (mirrors phase2_simplified.py exactly):
 *   For each of 4 ratio signals (IPC, MPKI, L2_PRESSURE, BRANCH_MISS_RATE):
 *     signal = computed from raw PMU counters
 *     rolling_mean  = mean  of signal over last W=10 samples
 *     rolling_std   = stdev of signal over last W=10 samples  (ddof=1)
 *     rolling_delta = signal[t] - signal[t-W]   (same as pandas diff(W))
 *   → 4 signals × 3 stats = 12 features
 *
 * Normalisation: z = (x - FEAT_MEAN[i]) / FEAT_STD[i]  (training-set stats)
 * Inference    : h1 = ReLU(W1 · z + b1)
 *                h2 = ReLU(W2 · h1 + b2)
 *                out = W3 · h2 + b3
 *                p   = sigmoid(out / T)
 * Decision     : attack if p >= MDL_THRESHOLD
 *
 * All weights come from model_weights.h (auto-generated by export_model_c.py).
 * No heap, no system calls — safe for EL2 interrupt context.
 *
 * For PC-side validation: compile with DETECTOR_PC_SIM defined to enable
 * the CSV-reading main() at the bottom of this file.
 *
 *   gcc -DDETECTOR_PC_SIM -O2 -o detector_sim detector.c && \
 *       ./detector_sim results/phase2_simplified/test_data.csv
 */

#include <arch/detector.h>
#include <arch/model_weights.h>

/* ── Bare-metal math ─────────────────────────────────────────────────────────
 * Raspberry Pi 4 (Cortex-A72) has hardware VFP/NEON, so float arithmetic
 * is single-cycle.  We only need exp and sqrt — implemented here without
 * <math.h> so the module is self-contained and linkable without libm.
 * ─────────────────────────────────────────────────────────────────────────── */

/**
 * bm_expf — Bare-metal e^x  (max relative error < 0.02% for |x| < 20)
 * Uses repeated squaring: exp(x) = ((1 + x/1024)^2)^10
 */
static float bm_expf(float x)
{
    if (x <= -20.0f) return 0.0f;
    if (x >=  20.0f) return 485165195.0f;
    float d = 1.0f + x * (1.0f / 1024.0f);
    /* 10 squarings = 2^10 = 1024 */
    d *= d; d *= d; d *= d; d *= d; d *= d;
    d *= d; d *= d; d *= d; d *= d; d *= d;
    return d;
}

/**
 * bm_sigmoidf — Numerically stable sigmoid: 1 / (1 + e^{-x})
 */
static float bm_sigmoidf(float x)
{
    return 1.0f / (1.0f + bm_expf(-x));
}

/**
 * bm_sqrtf — Bare-metal sqrt via one Newton-Raphson step on fast inverse sqrt.
 * Max relative error < 0.01% for positive inputs.
 */
static float bm_sqrtf(float x)
{
    if (x <= 0.0f) return 0.0f;
    /* Fast inverse sqrt (Quake III) */
    float xhalf = 0.5f * x;
    union { float f; unsigned int i; } u;
    u.f = x;
    u.i = 0x5f3759dfu - (u.i >> 1);
    float inv = u.f;
    inv = inv * (1.5f - xhalf * inv * inv);   /* 1 Newton step */
    inv = inv * (1.5f - xhalf * inv * inv);   /* 2nd step — extra precision */
    return x * inv;
}

#define BM_RELU(x)  ((x) > 0.0f ? (x) : 0.0f)


/* ── Per-CPU ring buffer state ───────────────────────────────────────────────
 * We maintain one ring buffer of W=MDL_WINDOW_SIZE scalars per signal per CPU.
 * The delta (diff(W)) is computed by saving the value that is about to be
 * overwritten (= the sample from exactly W steps ago) before writing the new
 * sample — see inline comments in detector_process_sample().
 * ─────────────────────────────────────────────────────────────────────────── */

#define N_SIGNALS 4   /* IPC, MPKI, L2_PRESSURE, BRANCH_MISS_RATE */

static float  s_ring[PMU_MAX_CPUS][N_SIGNALS][MDL_WINDOW_SIZE];
static int    s_idx[PMU_MAX_CPUS];      /* next-write position in ring       */
static int    s_filled[PMU_MAX_CPUS];   /* 1 once all W slots have been used */

/* ── Public API ─────────────────────────────────────────────────────────────── */

void detector_init(void)
{
    int c, s, w;
    for (c = 0; c < PMU_MAX_CPUS; c++) {
        s_idx[c]    = 0;
        s_filled[c] = 0;
        for (s = 0; s < N_SIGNALS; s++)
            for (w = 0; w < MDL_WINDOW_SIZE; w++)
                s_ring[c][s][w] = 0.0f;
    }
}

det_output_t detector_process_sample(cpuid_t cpu_id, const pmu_sample_t *sample)
{
    det_output_t result = { DET_WARMUP, 0.0f };

    if (cpu_id < 0 || cpu_id >= PMU_MAX_CPUS)
        return result;

    /* ── Step 1: compute 4 ratio signals from raw PMU counters ─────────────── */
    const float eps = 1e-9f;
    float sig_ipc    = (float)sample->instructions    / ((float)sample->cpu_cycles      + eps);
    float sig_mpki   = (float)sample->cache_misses    * 1000.0f
                     / ((float)sample->instructions   + eps);
    float sig_l2p    = (float)sample->l2_cache_access / ((float)sample->cpu_cycles      + eps);
    float sig_branch = (float)sample->branch_misses   / ((float)sample->instructions    + eps);

    float new_vals[N_SIGNALS] = { sig_ipc, sig_mpki, sig_l2p, sig_branch };

    /* ── Step 2: update ring buffer and compute per-signal stats ────────────── */
    int   idx = s_idx[cpu_id];
    float old_vals[N_SIGNALS]; /* = values from exactly W steps ago (for delta) */
    float mean_v[N_SIGNALS], std_v[N_SIGNALS], delta_v[N_SIGNALS];
    int   s;

    for (s = 0; s < N_SIGNALS; s++) {
        /* Save the value that is about to be overwritten.
         * When idx == head of ring (next to be written), the current
         * occupant ring[idx] is the sample from exactly W steps ago.  */
        old_vals[s]               = s_ring[cpu_id][s][idx];
        s_ring[cpu_id][s][idx]    = new_vals[s];

        /* Compute mean over the full ring buffer (W samples) — pass 1. */
        float sum = 0.0f;
        int   w;
        for (w = 0; w < MDL_WINDOW_SIZE; w++)
            sum += s_ring[cpu_id][s][w];
        mean_v[s] = sum / (float)MDL_WINDOW_SIZE;

        /* Sample std (ddof=1), matching pandas .std() used during training.
         * 2-pass algorithm: avoids catastrophic cancellation in 32-bit floats
         * on bare-metal AArch64 that caused the 1-pass formula to produce a
         * garbage negative variance and clamp std_v to 0.0f. */
        float sum_dev = 0.0f;
        for (w = 0; w < MDL_WINDOW_SIZE; w++) {
            float dev  = s_ring[cpu_id][s][w] - mean_v[s];
            sum_dev   += dev * dev;
        }
        float var  = sum_dev / (float)(MDL_WINDOW_SIZE - 1);
        std_v[s]   = bm_sqrtf(var > 0.0f ? var : 0.0f);

        /* delta = signal[t] - signal[t-W]  (old_vals[s] = signal[t-W]) */
        delta_v[s] = new_vals[s] - old_vals[s];
    }

    /* Advance ring index */
    s_idx[cpu_id] = (idx + 1) % MDL_WINDOW_SIZE;
    if (s_idx[cpu_id] == 0)
        s_filled[cpu_id] = 1;

    if (!s_filled[cpu_id])
        return result;   /* Still in warm-up period */

    /* ── Step 3: assemble 12-element feature vector ─────────────────────────── */
    /* Order must match RATIO_SIGNALS in phase2_simplified.py:
     * [IPC_mean, IPC_std, IPC_delta,  MPKI_mean, ...,  BRANCH_MISS_RATE_delta] */
    float feat[MDL_N_FEATURES];
    int   fi = 0;
    for (s = 0; s < N_SIGNALS; s++) {
        feat[fi++] = mean_v[s];
        feat[fi++] = std_v[s];
        feat[fi++] = delta_v[s];
    }

    /* ── Step 4: z-score normalisation (training-set mean and std) ──────────── */
    int i;
    for (i = 0; i < MDL_N_FEATURES; i++)
        feat[i] = (feat[i] - MDL_FEAT_MEAN[i]) / (MDL_FEAT_STD[i] + eps);

    /* ── Step 5: MLP forward pass ───────────────────────────────────────────── */
    float h1[MDL_N_H1], h2[MDL_N_H2];
    int   r, c;

    /* Layer 1: h1 = ReLU(W1 · feat + b1) */
    for (r = 0; r < MDL_N_H1; r++) {
        float acc = MDL_B1[r];
        for (c = 0; c < MDL_N_FEATURES; c++)
            acc += MDL_W1[r][c] * feat[c];
        h1[r] = BM_RELU(acc);
    }

    /* Layer 2: h2 = ReLU(W2 · h1 + b2) */
    for (r = 0; r < MDL_N_H2; r++) {
        float acc = MDL_B2[r];
        for (c = 0; c < MDL_N_H1; c++)
            acc += MDL_W2[r][c] * h1[c];
        h2[r] = BM_RELU(acc);
    }

    /* Output: logit = W3 · h2 + b3 */
    float logit = MDL_B3[0];
    for (c = 0; c < MDL_N_H2; c++)
        logit += MDL_W3[0][c] * h2[c];

    /* Temperature-calibrated sigmoid: p = sigmoid(logit / T) */
    float p = bm_sigmoidf(logit / MDL_TEMPERATURE);

    /* ── Step 6: threshold decision ─────────────────────────────────────────── */
    result.probability = p;
    result.status      = (p >= MDL_THRESHOLD) ? DET_ATTACK : DET_BENIGN;

    return result;
}


/* ══════════════════════════════════════════════════════════════════════════════
 * PC-SIDE SIMULATION / VALIDATION
 * Compile with: gcc -DDETECTOR_PC_SIM -O2 -o detector_sim detector.c
 * Run with    : ./detector_sim <csv_file>
 *
 * CSV format expected (same as training data):
 *   CPU_CYCLES,INSTRUCTIONS,CACHE_MISSES,BRANCH_MISSES,L2_CACHE_ACCESS,LABEL
 *   (header row is skipped automatically)
 *
 * Prints per-sample results and summary statistics.
 * ══════════════════════════════════════════════════════════════════════════════ */
#ifdef DETECTOR_PC_SIM

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char *argv[])
{
    const char *csv_path  = (argc > 1) ? argv[1] : "data/data17_clean.csv";
    const char *log_path  = "log_detector_sim.txt";
    const cpuid_t cpu_id  = 0;

    FILE *csv = fopen(csv_path, "r");
    if (!csv) {
        fprintf(stderr, "Error: cannot open '%s'\n", csv_path);
        return 1;
    }
    FILE *log = fopen(log_path, "w");
    if (!log)
        fprintf(stderr, "Warning: cannot create log file — printing to stdout only.\n");

    detector_init();

    /* Skip header line */
    char line[512];
    if (!fgets(line, sizeof(line), csv)) {
        fprintf(stderr, "Error: empty CSV file.\n");
        fclose(csv);
        if (log) fclose(log);
        return 1;
    }

    /* Counters for summary */
    long total = 0, warmup = 0, tp = 0, tn = 0, fp = 0, fn_cnt = 0;

    fprintf(stdout, "%-10s %-12s %-8s %-10s %s\n",
            "Sample", "Label", "p(atk)", "Status", "Verdict");
    fprintf(stdout, "%s\n",
            "------------------------------------------------------------------");
    if (log)
        fprintf(log, "%-10s %-12s %-8s %-10s %s\n",
                "Sample", "Label", "p(atk)", "Status", "Verdict");

    pmu_sample_t s;
    uint64_t label_raw;
    long line_no = 0;

    while (fgets(line, sizeof(line), csv)) {
        line_no++;
        /* Accept lines with 6 columns after timestamp (label may be absent) */
        int parsed = sscanf(line,
            "%*[^,],%llu,%llu,%llu,%llu,%llu,%llu",
            (unsigned long long *)&s.cpu_cycles,
            (unsigned long long *)&s.instructions,
            (unsigned long long *)&s.cache_misses,
            (unsigned long long *)&s.branch_misses,
            (unsigned long long *)&s.l2_cache_access,
            (unsigned long long *)&label_raw);

        if (parsed < 5) break;   /* end of data */
        int true_label = (parsed == 6) ? (int)label_raw : -1;  /* -1 = unknown */

        det_output_t out = detector_process_sample(cpu_id, &s);
        total++;

        const char *status_str, *verdict_str;

        if (out.status == DET_WARMUP) {
            warmup++;
            status_str  = "WARMUP";
            verdict_str = "—";
        } else {
            int predicted_attack = (out.status == DET_ATTACK) ? 1 : 0;
            /* true_label: 0 = benign, 2 = attack (CSV encoding) */
            int ground_truth = (true_label == 2) ? 1 : ((true_label == 0) ? 0 : -1);

            if (out.status == DET_ATTACK) {
                status_str = "ATTACK";
                if      (ground_truth == 1) { verdict_str = "[TP] Correct";    tp++;     }
                else if (ground_truth == 0) { verdict_str = "[FP] False alarm"; fp++;    }
                else                        { verdict_str = "[??] No label";             }
            } else {
                status_str = "BENIGN";
                if      (ground_truth == 0) { verdict_str = "[TN] Correct";    tn++;     }
                else if (ground_truth == 1) { verdict_str = "[FN] Missed!";    fn_cnt++; }
                else                        { verdict_str = "[??] No label";             }
            }
            (void)predicted_attack;
        }

        /* Print every 50th line to avoid flooding */
        if (line_no % 50 == 0 || out.status == DET_ATTACK) {
            fprintf(stdout, "%-10ld %-12s %-8.4f %-10s %s\n",
                    line_no,
                    (true_label == 2) ? "attack" : (true_label == 0) ? "benign" : "?",
                    out.probability, status_str, verdict_str);
            if (log)
                fprintf(log, "%-10ld %-12s %-8.4f %-10s %s\n",
                        line_no,
                        (true_label == 2) ? "attack" : (true_label == 0) ? "benign" : "?",
                        out.probability, status_str, verdict_str);
        }
    }

    long evaluated = total - warmup;
    fprintf(stdout, "\n%s\n", "==================================================================");
    fprintf(stdout, "SUMMARY — %s\n", csv_path);
    fprintf(stdout, "  Total samples  : %ld\n", total);
    fprintf(stdout, "  Warmup skipped : %ld  (W = %d)\n", warmup, MDL_WINDOW_SIZE);
    fprintf(stdout, "  Evaluated      : %ld\n", evaluated);
    if (evaluated > 0) {
        fprintf(stdout, "  TP             : %ld\n", tp);
        fprintf(stdout, "  TN             : %ld\n", tn);
        fprintf(stdout, "  FP             : %ld  (FPR = %.4f)\n",
                fp, (tn + fp) > 0 ? (float)fp / (float)(tn + fp) : 0.0f);
        fprintf(stdout, "  FN             : %ld  (Recall = %.4f)\n",
                fn_cnt, (tp + fn_cnt) > 0 ? (float)tp / (float)(tp + fn_cnt) : 0.0f);
    }
    fprintf(stdout, "  Threshold τ    : %.2f\n", MDL_THRESHOLD);
    fprintf(stdout, "  Temperature T  : %.4f\n", MDL_TEMPERATURE);
    fprintf(stdout, "%s\n", "==================================================================");

    if (log) {
        fprintf(log, "\nSUMMARY: TP=%ld TN=%ld FP=%ld FN=%ld  Recall=%.4f  FPR=%.4f\n",
                tp, tn, fp, fn_cnt,
                (tp + fn_cnt) > 0 ? (float)tp / (float)(tp + fn_cnt) : 0.0f,
                (tn + fp) > 0     ? (float)fp / (float)(tn + fp)     : 0.0f);
        fclose(log);
        fprintf(stdout, "\nLog saved to '%s'\n", log_path);
    }

    fclose(csv);
    return 0;
}

#endif /* DETECTOR_PC_SIM */
